import type { PrismaClient } from "@prisma/client";

import type { AppConfig } from "../infrastructure/config/env.js";
import type { AppLogger } from "../infrastructure/logging/app-logger.js";
import type { InMemoryMetricsRegistry } from "../infrastructure/telemetry/metrics-registry.js";
import type { TelemetryService } from "../infrastructure/telemetry/telemetry.service.js";
import type { AiRunRepository } from "../modules/ai/ai-run.repository.js";
import type { AiRunService } from "../modules/ai/ai-run.service.js";
import type { AnomalyScoreRepository } from "../modules/ai/anomaly-score.repository.js";
import type { AnomalyScoringService } from "../modules/ai/anomaly-scoring.service.js";
import type { DecisionExplanationRepository } from "../modules/ai/decision-explanation.repository.js";
import type { DecisionExplanationService } from "../modules/ai/decision-explanation.service.js";
import type { EnhancedForecastResultRepository } from "../modules/ai/enhanced-forecast-result.repository.js";
import type { ForecastEnhancementService } from "../modules/ai/forecast-enhancement.service.js";
import type { ModelRegistryRepository } from "../modules/ai/model-registry.repository.js";
import type { ModelRegistryService } from "../modules/ai/model-registry.service.js";
import type { AuthorizationService } from "../modules/authz/authz.service.js";
import type { BillingCheckoutService } from "../modules/billing/billing-checkout.service.js";
import type { BillingEntitlementService } from "../modules/billing/billing-entitlement.service.js";
import type { BillingPlanRepository } from "../modules/billing/billing-plan.repository.js";
import type { BillingPlanService } from "../modules/billing/billing-plan.service.js";
import type { BillingPortalService } from "../modules/billing/billing-portal.service.js";
import type { PlanSubscriptionRepository } from "../modules/billing/plan-subscription.repository.js";
import type { StripeEventLogRepository } from "../modules/billing/stripe-event-log.repository.js";
import type { StripeWebhookService } from "../modules/billing/stripe-webhook.service.js";
import type { UsageMeterRepository } from "../modules/billing/usage-meter.repository.js";
import type { UsageMeterService } from "../modules/billing/usage-meter.service.js";
import type { CatalogService } from "../modules/catalog/catalog.service.js";
import type { SkuRepository } from "../modules/catalog/sku.repository.js";
import type { AllocationDecisionService } from "../modules/decisioning/allocation-decision.service.js";
import type { DecisionArtifactRepository } from "../modules/decisioning/decision-artifact.repository.js";
import type { DecisionReadService } from "../modules/decisioning/decision-read.service.js";
import type { DecisionReasonRepository } from "../modules/decisioning/decision-reason.repository.js";
import type { DecisionRepository } from "../modules/decisioning/decision.repository.js";
import type { DecisionScoreRepository } from "../modules/decisioning/decision-score.repository.js";
import type { ExceptionDecisionService } from "../modules/decisioning/exception-decision.service.js";
import type { PolicyRepository } from "../modules/decisioning/policy.repository.js";
import type { PolicyService } from "../modules/decisioning/policy.service.js";
import type { ReplenishmentDecisionService } from "../modules/decisioning/replenishment-decision.service.js";
import type { CustomerOrderLineRepository } from "../modules/demand/customer-order-line.repository.js";
import type { CustomerOrderRepository } from "../modules/demand/customer-order.repository.js";
import type { CustomerOrderService } from "../modules/demand/customer-order.service.js";
import type { DemandSignalRepository } from "../modules/demand/demand-signal.repository.js";
import type { DemandSignalService } from "../modules/demand/demand-signal.service.js";
import type { HistoricalSaleRepository } from "../modules/demand/historical-sale.repository.js";
import type { SalesImportRunRepository } from "../modules/demand/sales-import.repository.js";
import type { SalesImportService } from "../modules/demand/sales-import.service.js";
import type { UserRepository } from "../modules/identity/user.repository.js";
import type { IntegrationAdapterRegistry } from "../modules/integrations/integration-adapter.registry.js";
import type { IntegrationConnectionRepository } from "../modules/integrations/integration-connection.repository.js";
import type { IntegrationConnectionService } from "../modules/integrations/integration-connection.service.js";
import type { IntegrationFailedRecordRepository } from "../modules/integrations/integration-failed-record.repository.js";
import type { IntegrationSourceRecordRepository } from "../modules/integrations/integration-source-record.repository.js";
import type { IntegrationSyncRunRepository } from "../modules/integrations/integration-sync-run.repository.js";
import type { IntegrationSyncService } from "../modules/integrations/integration-sync.service.js";
import type { BaselineForecastService } from "../modules/forecasting/baseline-forecast.service.js";
import type { ForecastJobProcessorService } from "../modules/forecasting/forecast-job-processor.service.js";
import type { ForecastJobRepository } from "../modules/forecasting/forecast-job.repository.js";
import type { ForecastJobService } from "../modules/forecasting/forecast-job.service.js";
import type { ForecastResultRepository } from "../modules/forecasting/forecast-result.repository.js";
import type { AuditEventRepository } from "../modules/audit/audit.repository.js";
import type { InventoryMovementRepository } from "../modules/inventory/inventory-movement.repository.js";
import type { InventoryPositionRepository } from "../modules/inventory/inventory-position.repository.js";
import type { InventoryRecomputationService } from "../modules/inventory/inventory-recomputation.service.js";
import type { InventoryReservationRepository } from "../modules/inventory/inventory-reservation.repository.js";
import type { InventoryService } from "../modules/inventory/inventory.service.js";
import type { InventoryTransferRepository } from "../modules/inventory/inventory-transfer.repository.js";
import type { LocationRepository } from "../modules/inventory/location.repository.js";
import type { LocationService } from "../modules/inventory/location.service.js";
import type { OutboxEventRepository } from "../modules/outbox/outbox.repository.js";
import type { DecisionOutcomeRepository } from "../modules/outcomes/decision-outcome.repository.js";
import type { DecisionOutcomeService } from "../modules/outcomes/decision-outcome.service.js";
import type { FillRateMeasurementRepository } from "../modules/outcomes/fill-rate-measurement.repository.js";
import type { FillRateService } from "../modules/outcomes/fill-rate.service.js";
import type { ForecastErrorMeasurementRepository } from "../modules/outcomes/forecast-error-measurement.repository.js";
import type { ForecastErrorService } from "../modules/outcomes/forecast-error.service.js";
import type { InventoryCostSnapshotRepository } from "../modules/outcomes/inventory-cost-snapshot.repository.js";
import type { InventoryCostSnapshotService } from "../modules/outcomes/inventory-cost-snapshot.service.js";
import type { InventoryHistoryService } from "../modules/outcomes/inventory-history.service.js";
import type { OutcomesProcessingService } from "../modules/outcomes/outcomes-processing.service.js";
import type { PolicyEffectivenessSummaryRepository } from "../modules/outcomes/policy-effectiveness-summary.repository.js";
import type { PolicyEffectivenessService } from "../modules/outcomes/policy-effectiveness.service.js";
import type { StockoutIncidentRepository } from "../modules/outcomes/stockout-incident.repository.js";
import type { StockoutDetectionService } from "../modules/outcomes/stockout-detection.service.js";
import type { ObservabilityService } from "../modules/observability/observability.service.js";
import type { WorkerRunRepository } from "../modules/observability/worker-run.repository.js";
import type { WorkerRunService } from "../modules/observability/worker-run.service.js";
import type { ExecutionAttemptRepository } from "../modules/execution/execution-attempt.repository.js";
import type { ExecutionProcessorService } from "../modules/execution/execution-processor.service.js";
import type { ExecutionTaskRepository } from "../modules/execution/execution-task.repository.js";
import type { ExecutionTaskService } from "../modules/execution/execution-task.service.js";
import type { IdempotencyKeyRepository } from "../modules/execution/idempotency-key.repository.js";
import type { SupportRepository } from "../modules/support/support.repository.js";
import type { SupportService } from "../modules/support/support.service.js";
import type { PurchaseOrderLineRepository } from "../modules/supply/purchase-order-line.repository.js";
import type { PurchaseOrderRepository } from "../modules/supply/purchase-order.repository.js";
import type { PurchaseOrderService } from "../modules/supply/purchase-order.service.js";
import type { SupplierLeadTimeStatRepository } from "../modules/supply/supplier-lead-time-stat.repository.js";
import type { SupplierPerformanceSnapshotRepository } from "../modules/supply/supplier-performance.repository.js";
import type { SupplierRepository } from "../modules/supply/supplier.repository.js";
import type { SupplierService } from "../modules/supply/supplier.service.js";
import type { SupplierSkuRepository } from "../modules/supply/supplier-sku.repository.js";
import type { SupplierSkuService } from "../modules/supply/supplier-sku.service.js";
import type { SupplyAnalyticsService } from "../modules/supply/supply-analytics.service.js";
import type { EntitlementRepository } from "../modules/tenancy/entitlement.repository.js";
import type { InvitationService } from "../modules/tenancy/invitation.service.js";
import type { OrganizationInvitationRepository } from "../modules/tenancy/invitation.repository.js";
import type { OrganizationMembershipRepository } from "../modules/tenancy/membership.repository.js";
import type { OrganizationRepository } from "../modules/tenancy/organization.repository.js";
import type { OrganizationService } from "../modules/tenancy/organization.service.js";
import type { RoleRepository } from "../modules/tenancy/role.repository.js";
import type { ApprovalTaskRepository } from "../modules/workflow/approval-task.repository.js";
import type { ApprovalTaskService } from "../modules/workflow/approval-task.service.js";
import type { DecisionWorkflowService } from "../modules/workflow/decision-workflow.service.js";
import type { OperatorOverrideRepository } from "../modules/workflow/operator-override.repository.js";
import type { OperatorOverrideService } from "../modules/workflow/operator-override.service.js";
import type { TransactionRunner } from "./transaction-runner.js";

export interface AppContainer {
  config: AppConfig;
  prisma: PrismaClient;
  transactionRunner: TransactionRunner;
  logger: AppLogger;
  metricsRegistry: InMemoryMetricsRegistry;
  telemetryService: TelemetryService;
  repositories: {
    aiRunRepository: AiRunRepository;
    anomalyScoreRepository: AnomalyScoreRepository;
    auditEventRepository: AuditEventRepository;
    approvalTaskRepository: ApprovalTaskRepository;
    billingPlanRepository: BillingPlanRepository;
    customerOrderLineRepository: CustomerOrderLineRepository;
    customerOrderRepository: CustomerOrderRepository;
    demandSignalRepository: DemandSignalRepository;
    decisionArtifactRepository: DecisionArtifactRepository;
    decisionOutcomeRepository: DecisionOutcomeRepository;
    decisionReasonRepository: DecisionReasonRepository;
    decisionRepository: DecisionRepository;
    decisionScoreRepository: DecisionScoreRepository;
    entitlementRepository: EntitlementRepository;
    forecastJobRepository: ForecastJobRepository;
    fillRateMeasurementRepository: FillRateMeasurementRepository;
    forecastErrorMeasurementRepository: ForecastErrorMeasurementRepository;
    forecastResultRepository: ForecastResultRepository;
    historicalSaleRepository: HistoricalSaleRepository;
    integrationConnectionRepository: IntegrationConnectionRepository;
    integrationFailedRecordRepository: IntegrationFailedRecordRepository;
    integrationSourceRecordRepository: IntegrationSourceRecordRepository;
    integrationSyncRunRepository: IntegrationSyncRunRepository;
    inventoryCostSnapshotRepository: InventoryCostSnapshotRepository;
    executionAttemptRepository: ExecutionAttemptRepository;
    executionTaskRepository: ExecutionTaskRepository;
    decisionExplanationRepository: DecisionExplanationRepository;
    enhancedForecastResultRepository: EnhancedForecastResultRepository;
    idempotencyKeyRepository: IdempotencyKeyRepository;
    inventoryMovementRepository: InventoryMovementRepository;
    inventoryPositionRepository: InventoryPositionRepository;
    inventoryReservationRepository: InventoryReservationRepository;
    inventoryTransferRepository: InventoryTransferRepository;
    invitationRepository: OrganizationInvitationRepository;
    locationRepository: LocationRepository;
    membershipRepository: OrganizationMembershipRepository;
    organizationRepository: OrganizationRepository;
    outboxEventRepository: OutboxEventRepository;
    operatorOverrideRepository: OperatorOverrideRepository;
    policyRepository: PolicyRepository;
    policyEffectivenessSummaryRepository: PolicyEffectivenessSummaryRepository;
    planSubscriptionRepository: PlanSubscriptionRepository;
    modelRegistryRepository: ModelRegistryRepository;
    purchaseOrderLineRepository: PurchaseOrderLineRepository;
    purchaseOrderRepository: PurchaseOrderRepository;
    roleRepository: RoleRepository;
    salesImportRunRepository: SalesImportRunRepository;
    skuRepository: SkuRepository;
    stockoutIncidentRepository: StockoutIncidentRepository;
    supplierLeadTimeStatRepository: SupplierLeadTimeStatRepository;
    supplierPerformanceSnapshotRepository: SupplierPerformanceSnapshotRepository;
    supplierRepository: SupplierRepository;
    supplierSkuRepository: SupplierSkuRepository;
    supportRepository: SupportRepository;
    stripeEventLogRepository: StripeEventLogRepository;
    userRepository: UserRepository;
    usageMeterRepository: UsageMeterRepository;
    workerRunRepository: WorkerRunRepository;
  };
  services: {
    aiRunService: AiRunService;
    allocationDecisionService: AllocationDecisionService;
    anomalyScoringService: AnomalyScoringService;
    approvalTaskService: ApprovalTaskService;
    authorizationService: AuthorizationService;
    billingCheckoutService: BillingCheckoutService;
    billingEntitlementService: BillingEntitlementService;
    billingPlanService: BillingPlanService;
    billingPortalService: BillingPortalService;
    baselineForecastService: BaselineForecastService;
    catalogService: CatalogService;
    customerOrderService: CustomerOrderService;
    demandSignalService: DemandSignalService;
    decisionExplanationService: DecisionExplanationService;
    decisionReadService: DecisionReadService;
    decisionWorkflowService: DecisionWorkflowService;
    decisionOutcomeService: DecisionOutcomeService;
    executionProcessorService: ExecutionProcessorService;
    executionTaskService: ExecutionTaskService;
    exceptionDecisionService: ExceptionDecisionService;
    fillRateService: FillRateService;
    forecastJobProcessorService: ForecastJobProcessorService;
    forecastJobService: ForecastJobService;
    forecastErrorService: ForecastErrorService;
    forecastEnhancementService: ForecastEnhancementService;
    integrationConnectionService: IntegrationConnectionService;
    integrationSyncService: IntegrationSyncService;
    inventoryCostSnapshotService: InventoryCostSnapshotService;
    inventoryHistoryService: InventoryHistoryService;
    inventoryRecomputationService: InventoryRecomputationService;
    inventoryService: InventoryService;
    invitationService: InvitationService;
    locationService: LocationService;
    organizationService: OrganizationService;
    operatorOverrideService: OperatorOverrideService;
    observabilityService: ObservabilityService;
    outcomesProcessingService: OutcomesProcessingService;
    policyService: PolicyService;
    policyEffectivenessService: PolicyEffectivenessService;
    modelRegistryService: ModelRegistryService;
    purchaseOrderService: PurchaseOrderService;
    replenishmentDecisionService: ReplenishmentDecisionService;
    salesImportService: SalesImportService;
    stockoutDetectionService: StockoutDetectionService;
    supportService: SupportService;
    supplierService: SupplierService;
    supplierSkuService: SupplierSkuService;
    supplyAnalyticsService: SupplyAnalyticsService;
    telemetryService: TelemetryService;
    stripeWebhookService: StripeWebhookService;
    usageMeterService: UsageMeterService;
    workerRunService: WorkerRunService;
  };
  integrationAdapterRegistry?: IntegrationAdapterRegistry;
}

declare module "fastify" {
  interface FastifyInstance {
    container: AppContainer;
  }
}
